version: '3.3'

services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "8089:80"

  php-fpm:
    container_name: my_blog_php
    build:
      context: docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

volumes:
  mysql:
